---
title: "Tidy Tuesday"
output: html_document
---



```{r}
library(tidyverse)
library(here)
library(janitor)
library(skimr)
library(sf)
library(mapview)
```
skimr::skim
```{r}
cats_uk <- read_csv("https://www.datarepository.movebank.org/bitstream/handle/10255/move.883/Pet%20Cats%20United%20Kingdom.csv?sequence=3") 
cats_uk_reference <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-01-31/cats_uk_reference.csv')
```

```{r}
tuesdata <- tidytuesdayR::tt_load('2023-01-31')
tuesdata <- tidytuesdayR::tt_load(2023, week = 5)

cats_uk <- tuesdata$cats_uk
cats_uk_reference <- tuesdata$cats_uk_reference
```
```{r}
mapTheme <- function(base_size = 12) {
  theme(
    text = element_text(color = "black", family="Avenir"),
    plot.title = element_text(size = 18,colour = "black", hjust = 0.5),
    plot.subtitle=element_text(face="italic", hjust = 0.5),
    plot.caption=element_text(size = 7, hjust = 0.5),
    axis.ticks = element_blank(),
    panel.background = element_blank(), 
    axis.text = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "white", fill=NA, size=2)
  )
}

```


```{r}
head(cats_uk)
```

```{r}
head(cats_uk_reference)
```

```{r}
skimr::skim(cats_uk)
```

```{r}
skimr::skim(cats_uk)
```

```{r}
cats_uk %>%
  group_by('tag_id') %>%
summarize(ground_speed = mean(ground_speed, na.rm=TRUE)) %>%
  left_join(cats_uk_reference, by='tag_id') %>%
  group_by(hunt, animal_reproductive_conditions, animal_sex) %>% 
  summarize(prey_p_month = mean(prey_p_month, na.rm=TRUE))

```
```{r}
cats_uk_reference %>% 
  group_by(hunt) %>% 
  summarize(prey_p_month = mean(prey_p_month, na.rm=TRUE))

```

```{r}
cats_uk_sf = cats_uk %>%
  left_join(cats_uk_reference, by='tag_id') %>%
  st_as_sf(.,coords=c("location_long", "location_lat"),crs=4326)
```

```{r}
mapview(cats_uk_sf %>% slice_sample(n=1000))
```


```{r}
ggplot() +
  geom_sf(data=cats_uk_sf, shape=21, size=3, aes(fill=ground_speed)) + 
  scale_fill_distiller(palette ="YlBlGn", name="Cat speed")
```

## uk map data
```{r}
uk <- map_data(map = "world", region = "UK") %>%
  filter(subregion == "Great Britain") 
```

  # st_as_sf(coords = c("long", "lat")) %>%
  # st_crop(., xmin = -5.758854, xmax = -4.208614, ymin = 50.10352, ymax = 50.88222, crs = 4326)


```{r}
ggplot(uk) +
  geom_polygon(fill = "gray", colour = "gray80", aes(x = long, y = lat, group = group)) +
  coord_map() +
  geom_sf(data = cats_uk_sf, shape = 21, size = 3, aes(fill = log(ground_speed))) +
  scale_fill_distiller(palette = "YlGnBu", name = "Cat Speed") +
  mapTheme()
```